"""Command-line interface for installation, hook dispatch, and diagnostics."""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
import tempfile
from pathlib import Path
from typing import Any, Sequence

from . import __version__
from .delivery import verify_azure_pull_request, verify_https_endpoint
from .evidence import EvidenceLedger
from .hooks import handle_event
from .installer import (
    OWNER,
    HOOK_TOPOLOGY,
    install_release,
    register_repository,
    uninstall_hooks,
    verify_hook_config,
    verify_release,
)
from .migration import audit_fleet, retire_legacy_hooks
from .models import DeliveryState, HookEvent
from .policy import (
    default_data_dir,
    effective_policy,
    load_global_policy,
    load_repository_policies,
    package_root,
    resolve_repo_context,
)
from .utils import atomic_write_json, canonical_path, load_json


MAX_EVENT_BYTES = 2_000_000
VERIFIABLE_DELIVERY_STATES = (
    DeliveryState.PR_OPEN,
    DeliveryState.PR_POLICY_READY,
    DeliveryState.MERGED,
    DeliveryState.RUNTIME_HEALTHY,
    DeliveryState.USER_PATH_VERIFIED,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="hookctl", description=__doc__)
    parser.add_argument("--version", action="version", version=__version__)
    parser.add_argument("--owner", default="")
    parser.add_argument("--manifest-digest", default="")
    subparsers = parser.add_subparsers(dest="command", required=True)

    event = subparsers.add_parser("event", help="Dispatch one Codex hook event from stdin.")
    event.add_argument("event_name", choices=[item.value for item in HookEvent])
    event.add_argument("--data-dir", type=Path)

    install = subparsers.add_parser("install", help="Install an immutable user-level release.")
    install.add_argument("--release-version", "--version", default=__version__)
    install.add_argument("--codex-home", type=Path)
    install.add_argument("--install-root", type=Path)
    install.add_argument("--mode", choices=("shadow", "enforce"), default="shadow")

    uninstall = subparsers.add_parser("uninstall", help="Remove only owned hook groups.")
    uninstall.add_argument("--codex-home", type=Path)
    uninstall.add_argument("--data-dir", type=Path)

    register = subparsers.add_parser(
        "register-repo",
        help="Bind a Git common directory to an immutable repository policy.",
    )
    register.add_argument("--repository-id", required=True)
    register.add_argument("--path", type=Path, required=True)
    register.add_argument("--mode", choices=("shadow", "canary", "enforce"), default="shadow")
    register.add_argument("--data-dir", type=Path)

    doctor = subparsers.add_parser("doctor", help="Verify installation and local state.")
    doctor.add_argument("--data-dir", type=Path)
    doctor.add_argument("--codex-home", type=Path)
    doctor.add_argument("--json", action="store_true")

    evidence = subparsers.add_parser("evidence", help="Read a privacy-safe session summary.")
    evidence.add_argument("--session", required=True)
    evidence.add_argument("--data-dir", type=Path)

    cleanup = subparsers.add_parser("cleanup", help="Apply evidence retention policy.")
    cleanup.add_argument("--retain-days", type=int, default=30)
    cleanup.add_argument("--data-dir", type=Path)

    audit = subparsers.add_parser(
        "audit-fleet",
        help="Inventory branch-controlled hooks and quarantine unsafe migration roots.",
    )
    audit.add_argument("--root", type=Path, action="append", required=True)
    audit.add_argument("--output", type=Path)

    retire = subparsers.add_parser(
        "retire-legacy",
        help="Preview or remove tracked legacy hooks in one clean task worktree.",
    )
    retire.add_argument("--path", type=Path, required=True)
    retire.add_argument(
        "--audit-receipt",
        type=Path,
        help="Fleet audit JSON generated by audit-fleet; required with --apply.",
    )
    retire.add_argument("--apply", action="store_true")

    verify = subparsers.add_parser(
        "verify-delivery",
        help="Perform explicit read-only verification and record one delivery state.",
    )
    verify.add_argument("--session", required=True)
    verify.add_argument(
        "--state",
        required=True,
        choices=[item.value for item in VERIFIABLE_DELIVERY_STATES],
    )
    verify.add_argument("--data-dir", type=Path)
    verify.add_argument(
        "--path",
        type=Path,
        required=True,
        help="Registered repository worktree used to bind provider evidence.",
    )
    source = verify.add_mutually_exclusive_group(required=True)
    source.add_argument("--ado-pr", type=int)
    source.add_argument("--url")

    subparsers.add_parser("self-test", help="Run an offline runtime smoke test.")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.owner and args.owner != OWNER:
        raise SystemExit(f"Unexpected hook owner: {args.owner}")
    if args.command == "event":
        return _event_command(args)
    if args.command == "install":
        return _print_result(
            install_release(
                version=args.release_version,
                codex_home=args.codex_home,
                install_root=args.install_root,
                default_mode=args.mode,
            )
        )
    if args.command == "uninstall":
        return _print_result(uninstall_hooks(codex_home=args.codex_home, data_dir=args.data_dir))
    if args.command == "register-repo":
        return _print_result(
            register_repository(
                args.path,
                args.repository_id,
                rollout_mode=args.mode,
                data_dir=args.data_dir,
            )
        )
    if args.command == "doctor":
        return _doctor_command(args)
    if args.command == "evidence":
        return _print_result(
            EvidenceLedger(args.data_dir or default_data_dir()).summaries(args.session)
        )
    if args.command == "cleanup":
        return _print_result(
            EvidenceLedger(args.data_dir or default_data_dir()).cleanup(args.retain_days)
        )
    if args.command == "audit-fleet":
        result = audit_fleet(args.root)
        if args.output:
            atomic_write_json(args.output, result)
        return _print_result(result if not args.output else result["summary"])
    if args.command == "retire-legacy":
        receipt: dict[str, object] | None = None
        if args.audit_receipt:
            loaded = load_json(args.audit_receipt)
            if not isinstance(loaded, dict):
                raise ValueError("Fleet audit receipt must be a JSON object.")
            receipt = loaded
        return _print_result(
            retire_legacy_hooks(
                args.path,
                apply=args.apply,
                audit_receipt=receipt,
            )
        )
    if args.command == "verify-delivery":
        return _verify_delivery_command(args)
    if args.command == "self-test":
        return _self_test()
    raise AssertionError(f"Unhandled command: {args.command}")


def _event_command(args: argparse.Namespace) -> int:
    raw = sys.stdin.read(MAX_EVENT_BYTES + 1)
    if len(raw) > MAX_EVENT_BYTES:
        return _emit_hook_failure(
            args.event_name,
            "HOOK_INPUT_TOO_LARGE",
            raw_event=raw,
        )
    if args.manifest_digest:
        integrity = verify_release(package_root(), args.manifest_digest)
        if not integrity.get("valid"):
            return _emit_hook_failure(
                args.event_name,
                "RELEASE_INTEGRITY_FAILURE",
                raw_event=raw,
            )
    try:
        payload = json.loads(raw)
        result = handle_event(
            args.event_name,
            payload,
            data_dir=args.data_dir or default_data_dir(),
        )
    except (json.JSONDecodeError, OSError, ValueError, sqlite3.Error) as exc:
        print(f"hookctl: {exc.__class__.__name__}", file=sys.stderr)
        return _emit_hook_failure(
            args.event_name,
            "HOOK_RUNTIME_FAILURE",
            raw_event=raw,
        )
    if result:
        json.dump(result, sys.stdout, ensure_ascii=True, separators=(",", ":"))
    return 0


def _doctor_command(args: argparse.Namespace) -> int:
    storage = canonical_path(args.data_dir or default_data_dir())
    install = load_json(storage / "install.json", {})
    home = canonical_path(args.codex_home or Path.home() / ".codex")
    hook_path = home / "hooks.json"
    hook_config = load_json(hook_path, {})
    release_result: dict[str, Any] = {"valid": False, "error": "not_installed"}
    hook_result: dict[str, Any] = {
        "valid": False,
        "owned_events": [],
        "failures": ["installation_state_unavailable"],
    }
    state_failures: list[str] = []
    if not isinstance(install, dict):
        state_failures.append("install_state_not_object")
    else:
        if install.get("schema_version") != 1:
            state_failures.append("schema_version_mismatch")
        if install.get("owner") != OWNER:
            state_failures.append("owner_mismatch")

        release_text = str(install.get("release_path", ""))
        interpreter_text = str(install.get("interpreter", ""))
        data_text = str(install.get("data_dir", ""))
        config_text = str(install.get("hook_config", ""))
        manifest_digest = str(install.get("manifest_digest", ""))

        release = Path(release_text)
        interpreter = Path(interpreter_text)
        if not release_text or not release.is_absolute():
            state_failures.append("release_path_not_absolute")
        if not interpreter_text or not interpreter.is_absolute() or not interpreter.is_file():
            state_failures.append("interpreter_invalid")
        if (
            not data_text
            or not Path(data_text).is_absolute()
            or canonical_path(Path(data_text)) != storage
        ):
            state_failures.append("data_dir_mismatch")
        if (
            not config_text
            or not Path(config_text).is_absolute()
            or canonical_path(Path(config_text)) != canonical_path(hook_path)
        ):
            state_failures.append("hook_config_path_mismatch")
        if len(manifest_digest) != 64 or any(
            value not in "0123456789abcdefABCDEF" for value in manifest_digest
        ):
            state_failures.append("manifest_digest_invalid")

        if release_text and release.is_absolute():
            release = canonical_path(release)
            release_result = verify_release(release, manifest_digest)
            if release_result.get("valid") and str(release_result.get("version", "")) != str(
                install.get("version", "")
            ):
                state_failures.append("version_mismatch")
        if (
            not state_failures
            and release_result.get("valid")
            and interpreter_text
            and interpreter.is_absolute()
        ):
            hook_result = verify_hook_config(
                hook_config,
                release=release,
                interpreter=canonical_path(interpreter),
                manifest_digest=manifest_digest,
                data_dir=storage,
            )

    state_result = {"valid": not state_failures, "failures": state_failures}
    ledger = EvidenceLedger(storage)
    with ledger.connect() as connection:
        quick_check = str(connection.execute("PRAGMA quick_check").fetchone()[0])
    policies = load_repository_policies()
    registrations = load_json(storage / "registrations.json", [])
    result = {
        "healthy": (
            release_result.get("valid") is True
            and state_result["valid"] is True
            and hook_result.get("valid") is True
            and quick_check == "ok"
        ),
        "version": install.get("version", "") if isinstance(install, dict) else "",
        "release": release_result,
        "installation_state": state_result,
        "hook_configuration": hook_result,
        "owned_events": hook_result.get("owned_events", []),
        "expected_events": [event.value for event, _ in HOOK_TOPOLOGY],
        "policy_count": len(policies),
        "registration_count": len(registrations) if isinstance(registrations, list) else 0,
        "sqlite_quick_check": quick_check,
        "trust": "user_review_required_or_user_managed",
        "network_in_event_handlers": False,
    }
    _print_result(result)
    return 0 if result["healthy"] else 1


def _verify_delivery_command(args: argparse.Namespace) -> int:
    storage = args.data_dir or default_data_dir()
    ledger = EvidenceLedger(storage)
    context = resolve_repo_context(args.path, storage)
    policy = effective_policy(context)
    state = DeliveryState(args.state)
    if args.ado_pr is not None:
        result = verify_azure_pull_request(
            ledger,
            session_id=args.session,
            context=context,
            policy=policy,
            state=state,
            pull_request_id=args.ado_pr,
        )
    else:
        result = verify_https_endpoint(
            ledger,
            session_id=args.session,
            context=context,
            policy=policy,
            state=state,
            url=args.url,
        )
    _print_result(result)
    return 0 if result.get("verified") else 1


def _self_test() -> int:
    global_policy = load_global_policy()
    repository_policies = load_repository_policies()
    with tempfile.TemporaryDirectory(prefix="codex-workflow-hooks-") as raw:
        ledger = EvidenceLedger(Path(raw))
        with ledger.connect() as connection:
            quick_check = str(connection.execute("PRAGMA quick_check").fetchone()[0])
    result = {
        "ok": bool(global_policy) and bool(repository_policies) and quick_check == "ok",
        "global_policy": str(global_policy.get("policy_id", "")),
        "repository_policy_count": len(repository_policies),
        "sqlite_quick_check": quick_check,
    }
    _print_result(result)
    return 0 if result["ok"] else 1


def _stop_hook_active(event_name: str, raw_event: str) -> bool:
    if event_name != HookEvent.STOP.value:
        return False
    try:
        payload = json.loads(raw_event)
    except (json.JSONDecodeError, TypeError):
        return False
    return isinstance(payload, dict) and payload.get("stop_hook_active") is True


def _emit_hook_failure(event_name: str, code: str, *, raw_event: str = "") -> int:
    if event_name == HookEvent.PRE_TOOL_USE.value:
        result = {
            "hookSpecificOutput": {
                "hookEventName": event_name,
                "permissionDecision": "deny",
                "permissionDecisionReason": (
                    f"{code}: central hook verification failed; mutation safety is unavailable."
                ),
            }
        }
        json.dump(result, sys.stdout, ensure_ascii=True, separators=(",", ":"))
    elif event_name == HookEvent.STOP.value and not _stop_hook_active(event_name, raw_event):
        json.dump(
            {
                "decision": "block",
                "reason": f"{code}: central evidence gate could not be evaluated.",
            },
            sys.stdout,
            ensure_ascii=True,
            separators=(",", ":"),
        )
    return 0


def _print_result(result: Any) -> int:
    json.dump(result, sys.stdout, indent=2, sort_keys=True, ensure_ascii=True)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
